import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Topbar from "@/components/shared/Topbar";
import Bottombar from "@/components/shared/Bottombar";
import LeftSidebar from "@/components/shared/LeftSidebar";
import RightSidebar from "@/components/shared/RightSidebar";

import { getCurrentUser } from "@/actions/user.action";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "声呐元 - 链上IP天使孵化与授权",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const { user } = await getCurrentUser();

  const userInfo = {
    userId: user ? user.id : "",
    username: user ? user.username : "",
    avatar: user ? user.avatar : "",
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <Topbar {...userInfo} />

        <main className="flex flex-row">
          <LeftSidebar loginStatus={user ? true : false} />

          <section className="main-container">{children}</section>

          <RightSidebar />
        </main>

        <Bottombar />
      </body>
    </html>
  );
}
