import "./globals.css";
import type { Metadata } from "next";

import Topbar from "@/components/shared/Topbar";
import Bottombar from "@/components/shared/Bottombar";
import RightSidebar from "@/components/shared/RightSidebar";
import RainbowKit from "@/components/wallet/RainbowKit";

import { getCurrentUser } from "@/actions/user.action";

export const metadata: Metadata = {
  title: "SonarMeta - On-chain IP authorization and value captured network",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const { user } = await getCurrentUser();

  const userInfo = {
    address: user ? user.address : "0x",
    username: user ? user.username : "",
    avatar: user ? user.avatar : "",
    bio: user ? user.bio : "",
  };

  return (
    <html lang="en">
      <body>
        <RainbowKit>
          <Topbar {...userInfo} />

          <main>
            <RightSidebar loginStatus={user ? true : false} />
            <section className="main-container">{children}</section>
          </main>

          <Bottombar />
        </RainbowKit>
      </body>
    </html>
  );
}
