import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import RainbowKit from "@/components/wallet/RainbowKit";

import Topbar from "@/components/shared/Topbar";
import Bottombar from "@/components/shared/Bottombar";
import RightSidebar from "@/components/shared/RightSidebar";

import { getCurrentUser } from "@/actions/user.action";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SonarMeta - On-chain IP angel nurturing and authorization network.",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const { user } = await getCurrentUser();

  const userInfo = {
    address: user ? user.address : "0x",
    username: user ? user.username : "",
    avatar: user ? user.avatar : "",
    bio: user ? user.bio : "",
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <RainbowKit>
          <Topbar {...userInfo} />

          <main>
            <RightSidebar loginStatus={user ? true : false} />
            <section className="main-container">{children}</section>
          </main>

          <Bottombar />
        </RainbowKit>
      </body>
    </html>
  );
}
