// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Marketplace$Type } from "./Marketplace";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Marketplace"]: Marketplace$Type;
    ["contracts/Marketplace.sol:Marketplace"]: Marketplace$Type;
  }
}
